[package]
name = "rustboy"
version = "0.1.0"
authors = ["Lewis Hogan <lewishogan@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.2.0"